#!/usr/bin/env bash
# Deploy candidate, step 4a: records the image set in candidata/imagem.txt (same format as candidata-imagem.sh) and
# one CycloneDX SBOM per image (candidata/sbom-<servico>.json), generated by Trivy from the pushed digest, and the
# checksums file the provenance attestation signs (candidata/imagens.sha256: "<digest> <imagem>").
# Environment: IMAGEM (servico=imagem@sha256:…,… or a bare imagem@sha256:…), RUNNER_TEMP, BB.
set -euo pipefail
shopt -s inherit_errexit
trap 'echo "::error::$(basename "$0") falhou na linha $LINENO (código $?)" >&2' ERR
AQUI="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IFS=',' read -r -a itens <<<"${IMAGEM:?}"
mkdir -p candidata
: > candidata/imagens.sha256
linhas=()
trivy=$(bash "$AQUI/trivy.sh")
for item in "${itens[@]}"; do
  if [[ "$item" == *=* ]]; then nome="${item%%=*}"; imagem="${item#*=}"; else nome=app; imagem="$item"; fi
  [[ "$imagem" =~ @sha256:([0-9a-f]{64})$ ]] || { echo "::error::IMAGEM sem digest: $item"; exit 1; }
  echo "${BASH_REMATCH[1]}  ${imagem%@*}" >> candidata/imagens.sha256
  "$trivy" image --quiet --format cyclonedx --output "candidata/sbom-$nome.json" "$imagem"
  linhas+=("$nome=$imagem")
done
if [ "${#linhas[@]}" -eq 1 ] && [ "${linhas[0]%%=*}" = app ]; then linhas=("${linhas[0]#*=}"); fi
printf '%s\n' "${linhas[@]}" > candidata/imagem.txt
echo "Registro: $(wc -l < candidata/imagem.txt) imagem(ns), SBOM de cada uma."
